[workspace]
channels = ["conda-forge"]
name = "lmd"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.12.*"
pandas = ">=2.3.3,<3"
polars = ">=1.35.1,<2"
numpy = ">=2.3.4,<3"
scikit-image = ">=0.25.2,<0.26"
tqdm = ">=4.67.1,<5"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
cellpose = ">=4.0.7,<5"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
napari = { version = ">=0.6.6, <0.7", extras = ["all"] }
bioio = ">=3.0.0, <4"
bioio-ome-tiff = ">=1.4.0, <2"
py-lmd = ">=1.0.0, <2"
bioio-tifffile = ">=1.3.0, <2"
